name = input("Enter your name: ")
height = input("What is your heigth: ")
age = input("What is your age: ")
print(f"Your name is, {name} your height is {height} your age is {age}.")
print(f"thank {name} to give me your information.")